CREATE TABLE news_articles (
    uri VARCHAR(50) PRIMARY KEY,
    lang VARCHAR(10),
    is_duplicate BOOLEAN,
    article_date DATE,
    article_time TIME,
    date_time TIMESTAMPTZ,
    date_time_pub TIMESTAMPTZ,
    data_type VARCHAR(50),
    sim NUMERIC,
    url TEXT,
    title TEXT,
    body TEXT,
    source JSONB,
    authors JSONB,
    concepts JSONB,
    categories JSONB,
    image TEXT,
    event_uri VARCHAR(50),
    sentiment NUMERIC(12,10),
    wgt BIGINT,
    relevance INT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);